# REST Client
# https://github.com/Huachao/vscode-restclient/blob/master/README.md

### 探测指定x,y位置的距离, 返回数据通过`websocket`的`notify_gcode_response`事件获取
@api = http://lx2-0d9a34.local
POST {{api}}/printer/gcode/script
content-type: application/json

{
    "script": "PROBE_POINT X=10 Y=23"
}

# notify_gcode_response
#
# 正常返回↓
# {
#     "jsonrpc": "2.0",
#     "method": "notify_gcode_response",
#     "params": [
#         "{\"code\": \"PROBE_POINT\", \"msg\": \"OK\", \"data\": \"x=10.0 y=23.0 z=74.4\"}"
#     ]
# }
# 
# 异常返回(情况1), 忽略处理, 这是后端的日志↓
# {
#     "jsonrpc": "2.0",
#     "method": "notify_gcode_response",
#     "params": [
#         "// wake up fill_light_value=1.0"
#     ]
# }
# 
# 异常返回(情况2), 此时需要调用重启MCU`firmware_restart`接口↓
# {
#     "jsonrpc": "2.0",
#     "method": "notify_gcode_response",
#     "params": [
#         "!! MCU 'mcu' shutdown: Timer too close"
#     ]
# }

### 服务器状态查询
@api = http://lx2-0d9a34.local
GET {{api}}/server/info

# {
#   "result": {
#     "klippy_connected": true,
#     "klippy_state": "ready",
#     "components": [
#       "klippy_connection",
#       "application",
#       "websockets",
#       "internal_transport",
#       "dbus_manager",
#       "database",
#       "file_manager",
#       "klippy_apis",
#       "secrets",
#       "template",
#       "shell_command",
#       "machine",
#       "data_store",
#       "proc_stats",
#       "job_state",
#       "job_queue",
#       "http_client",
#       "announcements",
#       "webcam",
#       "extensions",
#       "update_manager",
#       "safe_check",
#       "wifi_customer_conf",
#       "temp_control",
#       "authorization",
#       "zeroconf"
#     ],
#     "failed_components": [],
#     "registered_directories": [
#       "config",
#       "zip_file",
#       "logs",
#       "gcodes",
#       "config_examples",
#       "docs"
#     ],
#     "warnings": [],
#     "websocket_count": 2,
#     "homed_axes": "xyz",
#     "firmware_version": "LX2-V90007-1.0.7-25:04:02",
#     "firmware_name": "LX2",
#     "firmware_code": 90000,
#     "firmware_data": "24:12:10_17:26:33",
#     "firmware_hardware": "240820",
#     "moonraker_version": "LX2-V90007-1.0.7-25:04:02"
#   }
# }


### 按照指定速度(mm/min)预览多个矩形位置
@api = http://lx2-0d9a34.local
POST {{api}}/printer/print/Preview
content-type: application/json

{
    "speed": 16000,
    "objlist": [
        {
            "coord_x": 100,
            "coord_y": 100,
            "obj_w": 1,
            "obj_h": 1
        }
    ]
}

# {
#   "result": "ok"
# }

### 停止预览
@api = http://lx2-0d9a34.local
POST {{api}}/printer/print/stopPreview

# {
#   "result": "ok"
# }


### 执行GCode脚本, `script`内容就是要执行的GCode指令, 注意用`\n`结尾
@api = http://lx2-0d9a34.local
POST {{api}}/printer/gcode/script
content-type: application/json

{
    "script": "G0 X0 Y0\n"
}

# {
#   "result": "ok"
# }

### 重启MCU固件
@api = http://lx2-0d9a34.local
POST {{api}}/printer/firmware_restart

# {
#     "result": "ok"
# }

# {
#     "jsonrpc": "2.0",
#     "method": "notify_gcode_response",
#     "params": [
#         "// Klipper state: Disconnect"
#     ]
# }

### 重启Klipper
@api = http://lx2-0d9a34.local
POST {{api}}/printer/restart

# {
#     "result": "ok"
# }

# {
#     "jsonrpc": "2.0",
#     "method": "notify_klippy_disconnected"
# }

# {
#     "jsonrpc": "2.0",
#     "method": "notify_gcode_response",
#     "params": [
#         "// Klipper state: Disconnect"
#     ]
# }

### 查询固件版本信息
@api = https://alternate.hingin.com
POST {{api}}/apply/getUpgradeApplyByVersion
content-type: application/json

{
    "version": "90010",
    "type": 0
}

# {
#   "errMsg": "操作成功",
#   "code": 200,
#   "data": {
#     "name": "90010",
#     "versionCode": 90010,
#     "type": 16,
#     "path": "https://oss.laserpecker.net/apply/firmware/LX2_V90010.zip",
#     "description": "1.Fix known bugs\r\n2.Fix known bugs\r\n3.Fix known bugs\r\n4.Fix known bugs",
#     "descriptionEn": "1.Fix known bugs\r\n2.Fix known bugs\r\n3.Fix known bugs\r\n4.Fix known bugs",
#     "version": "9.0010",
#     "isOpenDowngrade": 1,
#     "createTime": "2025-04-09 18:20:31",
#     "detailsList": null
#   }
# }

### 固件升级
@api = http://lx2-0d9a34.local
POST {{api}}/server/files/upload
Content-Type: multipart/form-data; boundary=--------------------------------angcyo

--------------------------------angcyo
Content-Disposition: form-data; name="root"
zip_file
--------------------------------angcyo
Content-Disposition: form-data; name="type"
update
--------------------------------angcyo
Content-Disposition: form-data; name="file"; filename="LX2_V90010.zip"
< ./LX2_V90010.zip
--------------------------------angcyo--

# {
#     "action": "create_file",
#     "item": {
#         "modified": 1747641947.3215744,
#         "size": 40679743,
#         "permissions": "rw",
#         "path": "LX2_V90010.zip",
#         "root": "zip_file"
#     }
# }

### 清除激光器打印时间
@api = http://lx2-0d9a34.local
POST {{api}}/server/laserTimeClean

# {
#   "result": {
#     "state": "okay"
#   }
# }